title: FFXIV Primer
description: A primer for new players to Final Fantasy XIV.
theme: just-the-docs

url: https://poysama.github.io/ffxiv-primer

aux_links:
  Template Repository: https://github.com/poysama/ffxiv-primer

color_scheme: dark

nav_enabled: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

collections:
  endgame:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    endgame:
      name: Endgame content
